FROM criyle/go-judge:v1.9.9 AS go-judge 

FROM debian:12

WORKDIR /opt

RUN apt-get update && \
    apt-get install -y gcc-12 g++-12 openjdk-17-jdk python3.11 pypy3 && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=go-judge /opt/go-judge /opt/mount.yaml /opt/

RUN sed -i 's/java 21/java 17/g' mount.yaml && \
    sed -i 's/java-21-openjdk/java-17-openjdk/g' mount.yaml

EXPOSE 5050/tcp 5052/tcp

ENTRYPOINT ["./go-judge"]
